### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by SimonMJC** [DDANGEUN/BluetoothClassic_MVVM#1]
안녕하세요 ! 블로그 보면서 구현하다가 깃에서도 같이 보면서 구현하고 있는 중입니다! 
혹시 제가 mvvm 을 적용하지 않은 상태에서 구현해주신 함수 중심으로 구현을 했는데요, 디바이스 스캔 및 기기 찾기 이후에 
소켓 생성하고 연결하는 부분에서 socketFail이 뜨는데 이 부분에 대해서 이틀 넘게 삽질하고 있어서 질문 몇가지 드려도 되나 이슈로 남깁니다 ㅜ

**Comment by DDANGEUN** [comment]
안녕하세요. 너무  늦게 확인했는데. 해결하셨나요?  이 레포는 ble가 아닌 classic 버전입니다.

**Comment by SimonMJC** [comment]
앗 네네 저 당시에 잘 몰라서 질문 드렸었는데, 잘 해결했습니다:) 덕분에 블루투스 이해하는데에 도움이 많이 됬어요! 감사합니다 ㅎㅎ
